### PR TITLE
add mutating joins

### PR DESCRIPTION
**Pull request by bleearmstrong**
This should implement the four mutating joins (left, right, inner, outer/full).
I did have to modify the @ApplyToDataframe function slightly.
The functions were tested with the dplyr two-table verbs vignette (https://cran.r-project.org/web/packages/dplyr/vignettes/two-table.html) and achieved the same output.
djoin was used as the generic name so as to not pollute the namespace.

### CODE REVIEW

**Comment by dodger487** [comment]
This is really great, thanks for working on this.  I have two main suggestions before merging.

**First**, can you add the python-version of the dplyr two-table verb tests to test.py?

**Second**, I'd like to avoid using strings of computation whenever possible. I think it's possible to use Laters (or 2-tuples of strings) instead of the `"colA=colB"` syntax.
Idea 1:
`flights2 >> inner_join(airports, by=[(X.dest, X.faa)])`

Idea 2:
`flights2 >> inner_join(airports, by=[("dest", "faa")])`

Idea 3 (use a dict, closer to dplyr style):
`flights2 >> inner_join(airports, by={"dest": "faa"})`

Note that if we use Laters, we could allow joining on columns that don't exist:
`flights2 >> inner_join(other_flights, by=X.hour // 8)`
For example, this would join on breaking hours into three groups (12am-8am, 8am-4pm, 4pm-12am)

What do you think?

**Comment by bleearmstrong** [comment]
Regarding the first, yes, I can work on that.
Regarding the second, I think Idea 2 is most consistent with dplyr syntax, but I definitely see the benefits to being able to use functions (although as far as I know, neither dplyr nor pandas let you do this; and now that I think about it, what I wrote are basically wrapper functions that call on built-in pandas functions, so I'm not sure if this will translate).  
On the other hand, I like the idea of using strings, since you can then use variables if you want to. Implementing Idea 2 or 3 probably won't be too much work, but I'm not sure about Idea 1. I will look into it.
Personally, I would vote for Idea 2, then Idea 3, then Idea 1, but this is your project.

**Comment by dodger487** [comment]
Okay, let's stick with Idea 2-- if you implement that and tests, I'll merge, and then I can add in Laters (idea 1) at some point if I decide it's a good idea to have that as well.

**Comment by bleearmstrong** [comment]
I've made the requested changes, using Idea 2.

**Comment by dodger487** [comment]
Great, thank you!

**Pull request merged**
