### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by Nagasaki45**
Hi, the main improvement here is the addition of python 3 support. Apart from that:
- Add travis-ci for continuous integration ([the entire test suite passes on python 2.7 and 3.3/4/5](https://travis-ci.org/Nagasaki45/dplython)).
- Fix TestMutates.test_multi issue #5.

### CODE REVIEW

**Comment by dodger487** [comment]
This looks great-- I have two small requests:
- Can you update the README.md to remove where it says "I wrote this for Python 2.7 because I'm a bad person. Python 3 version coming soon."
- I think this is worth changing the version number from 0.0.1 to 0.0.2 in setup.py

**Comment by Nagasaki45** [comment]
Thanks for the comments @dodger487. Anything else?

**Comment by dodger487** [comment]
Thank you!

**Comment by Nagasaki45** [comment]
Are you using travis-ci? Everything is ready, you just need to mark this repo in travis-ci and the test suite will run automatically on every push / PR.

**Comment by dodger487** [comment]
Thanks for the tip. I did not have travis-ci turned on, but it is now, so we should see it moving forward.

**Pull request merged**
